app:
  Version: 1.0.0
  Mode: development
  Port: 4000
  Secret: go-courses
aws:
  Region: ap-northeast-1
  APIKey: AKIAZINF6DDK7IJ4HFXZ
  SecretKey: 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
  S3Domain: https://d338hmodjsosv2.cloudfront.net
  S3Bucket: courses-storages
