app:
  Version: 1.0.0
  Mode: development
  Port: 4000
  Secret: go-courses
aws:
  Region: ap-northeast-1
  APIKey: AKIAZINF6DDKUQ7MR6FY
  SecretKey: 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
  S3Domain: https://d338hmodjsosv2.cloudfront.net
  S3Bucket: courses-storages
