app:
  Version: 1.0.0
  Mode: development
  Port: 4000
  Secret: go-courses
aws:
  Region: ap-northeast-1
  S3Domain: https://d338hmodjsosv2.cloudfront.net
  S3Bucket: courses-storages
otherServices:
  DurationVideo: localhost:4004

